### ISSUE TITLE
Failed sending Rudder PGN

### ISSUE THREAD

**Issue by Lukemarino** [usna-sailbot/bridge-2020#4]
I think the Rudder and Bridge programs are close. When testing the bridge node by itself, the Spektrum receiver gets the proper message and packs it into the frame and successfully sends the message; however, when connected to the CAN bus and a 12v power supply is connected, the Frames abruptly fail to send. It seems like a hardware issue but I'm not entirely sure because I have never encountered the problem before. I attached an image of what the bridge node outputs to teraterm before and after power is connected to the CAN.

![Annotation](https://user-images.githubusercontent.com/37090182/69282163-a1d17180-0bb7-11ea-9b1d-36990e560367.png)

**Comment by Lukemarino** [comment]
I replaced every part in the physical CAN bus and I still receive the same error so it must be a problem with my bridge node program.

**Comment by devangel77b** [comment]
I am able to replicate this on a pure SY202 rig so it is not a problem with in hull physical CAN bus.

**Comment by devangel77b** [comment]
Rudder node appears not to be receiving anything.

**Comment by devangel77b** [comment]
Confirmed problem is in rudder-2020/main.cpp somewhere; if I load the rudder_rx test code directly the system works fine.

**Comment by devangel77b** [comment]
1. The nmea 2000 bus is connected to the rudder node mbed using CAN hi and lo pins at p30, p29.
2. However, line 21 of main.cpp attempts to also assign p30 as a DigitalOut for driving the sleep line of the stepper motor driver. I believe this would cause CAN transmit/receive on the rudder node to break.

**Comment by devangel77b** [comment]
In addition, rudder-2020/main.cpp was missing a line to #include "rtos.h" which I think is required.

**Comment by devangel77b** [comment]
p30 being defined as DigitalOut would also result in the oscilloscope traces observed by CDR Frontera.
